# Generated by Django 3.1.6 on 2021-02-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='street',
            new_name='address',
        ),
    ]
