# Generated by Django 3.1.6 on 2021-02-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_confirm_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobilenumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='parish',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='trnnumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
