# Generated by Django 3.1.6 on 2021-02-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20210214_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='FL_addr1',
            field=models.CharField(blank=True, default='x', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='FL_addr2',
            field=models.CharField(blank=True, default='x', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='FL_city',
            field=models.CharField(blank=True, default='x', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='FL_phonenumber',
            field=models.CharField(blank=True, default='x', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='FL_state',
            field=models.CharField(blank=True, default='x', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='FL_zipcode',
            field=models.CharField(blank=True, default='x', max_length=100),
        ),
    ]
